services:
  user-service:
    build:
      context: ./
      dockerfile: ./docker/user-service/dockerfile
    container_name: user-service
    environment:
      - MONGODB_URI=${MONGODB_URI_USER}
      - JWT_KEY=${JWT_KEY}
    volumes:
      - ./user-service:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db-user

  db-user:
    image: mongo:7.0.14
    container_name: db-user
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE_USER}
      # - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    # volumes:
    # - mongodb_data:/data/db
    # - ./mongodb/mongod.conf:/etc/mongod.conf
    # - ./mongodb/mongod/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    ports:
      - "27017:27017"
